FROM node:alpine

WORKDIR /app

COPY ./package*.json /app

RUN npm install

COPY . .

FROM node:slim
# We don't need the standalone Chromium
# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
# Copy the app directory from the builder stage
COPY --from=builder /app /app

WORKDIR /app


EXPOSE 9002

CMD [ "node", "index.js" ]